### ISSUE TITLE
@array validation does not work on empty objects.

### ISSUE THREAD

**Issue by ste2425** [moshegottlieb/ts-json-object#4]
If a class field is decorated as an array and only recieves an object when validation is run that object will be wrapped in an Array and pass validation.

No validation will be run on the object within that array.

Consider the following:

```ts
class Child extends JSONOBject {
    @required
    fieldOne: string;
}

class Parent extends JSONObject {
    @required
    field: string;

    @array(Child)
    children: Child[];
}

new Parent({
    field: 'good string',
    children: {}
});
```
The children field is marked as an array of `Child` and so the example JSON should fail. However it does not. The empty Object recieved is ~~converted to~~ wrapped in an array, but then validation not run on that object to ensure it conforms to the class `Child`.

The issue appears to related to logic flow here: https://github.com/moshegottlieb/ts-json-object/blob/master/src/json_object.ts#L30

`value` is the empty object and `design_type` is Array. As the value is an object but not array it falls into the else of `new design_type(value)`.

This is where the wrapping with an Array happens. However from this point the element that has wrapped does not run validation. I haven't been able to track down that part of the problem.

**Comment by moshegottlieb** [comment]
Resolved in 9293afe
