### ISSUE TITLE
Review what impact official ES Decorators will have

### ISSUE THREAD

**Issue by ste2425** [moshegottlieb/ts-json-object#7]
Decorators has reached stage 3 and will/has been implemented for v5 of TypeScript which is set to be released next month.

https://github.com/microsoft/TypeScript/pull/50820

The ES decorators has some breaking changes compared to the legacy experimental decorators implementation.

As this library (we find it very useful BTW) relies on decorators i'm not entirely sure what, if anything, will need to change but its worth a review to check. 

I suspect at some point the old decorators will be deprecated in favour of the standard version.

**Comment by moshegottlieb** [comment]
Thanks!
I've seen it in the typescript beta release notes, this is definitely on my todo list.

**Comment by moshegottlieb** [comment]
At the moment, you still need  `"experimentalDecorators": true` and  `"emitDecoratorMetadata": true` in your `tsconfig.json`.  
It will work with newer versions of typescript, but the new decorator syntax would not, these are at the moment mutually exclusive.  
If you are using the new style decorators of typescript 5, you may want to move the JSON validation to a different module which do not.  
Currently, while exists in the interface, the new decorators bear no metadata about properties, but the documentation suggests this may change in the future.  
Until such time arrives, if it ever does, this issue cannot be resolved, and therefore is now closed.

**Comment by ste2425** [comment]
Hi.

I know this is an old issue but was re-visiting this library (doing a tech talk on it at a different company to where i first used it) and figured id see if the landscape of ESDecorators has changed at all regarding the meta data TSDecorators made available.


There's been a proposal here to support it and an interesting ensuing conversation.

https://github.com/microsoft/TypeScript/issues/57533

Not sure if this library is still regularly worked on or considered feature complete currently but thought id mention it :)
